Add support for CacheControl header
drone-plugins/drone-s3-sync pull request #26
Opened 2016-10-19 17:59 UTC by brianfoshee

This PR adds support for a `cache_control` key. 

Fixes #18

2016-10-19 18:53 UTC, nlf requested changes

2016-10-19 18:53 UTC, nlf commented on DOCS.md
> +In the  `cache_control` field the key is an extension including the leading dot `.`. If you want to set cahce control for files with no extension, set the key
nit, `cahce` -> `cache`

2016-10-19 18:53 UTC, nlf commented on DOCS.md
> +to th empty string `""`. If there are no matches for the `cache_control` of a file, no cache-control header will be added.
nit, `to th empty` -> `to the empty`

2016-10-19 19:23 UTC, brianfoshee commented on DOCS.md
> +to th empty string `""`. If there are no matches for the `cache_control` of a file, no cache-control header will be added.
Fixed

2016-10-19 19:23 UTC, brianfoshee commented on DOCS.md
> +In the  `cache_control` field the key is an extension including the leading dot `.`. If you want to set cahce control for files with no extension, set the key
fixed

2016-10-19 20:10 UTC, nlf commented
LGTM

2016-10-19 21:51 UTC, tboerger commented on DOCS.md
> -        Cache-Control: "max-age: 10000000"
No further cache control example anymore?

2016-10-19 21:55 UTC, brianfoshee commented on DOCS.md
> -        Cache-Control: "max-age: 10000000"
These didn't properly set the `Cache-Control` header - just `x-amz-meta-cache-control`. See line 49 for the new example.

2016-10-20 10:24 UTC, tboerger approved these changes

2016-10-20 10:24 UTC, tboerger commented
LGTM

2016-10-24 15:49 UTC, brianfoshee commented
@nlf @tboerger is this good to be merged in?

2016-11-02 08:18 UTC, tboerger commented
I have already approved, just waiting for a comment of @nlf

2016-11-02 13:45 UTC, nlf commented
I commented before you :) I'm fine with it. On mobile right now, but someone else is free to merge

2016-11-02 13:54 UTC, merged

2017-03-31 19:11 UTC, brianfoshee commented
@nlf @tboerger is there any way to get this rebuilt for docker hub? It looks like this image is old https://hub.docker.com/r/plugins/drone-s3-sync/

2017-03-31 19:23 UTC, nlf commented
tried the one at https://hub.docker.com/r/plugins/s3-sync ?

2017-03-31 21:11 UTC, brianfoshee commented
I have not - is that the same plugin, just a different image?

2017-03-31 21:12 UTC, nlf commented
yup, some months ago plugins started getting pushed to different names

2017-03-31 21:12 UTC, brianfoshee commented
great, thanks!

2017-04-03 15:48 UTC, brianfoshee commented
@nlf I'm getting this error message using the new image: 

```
[info] Pulling image plugins/s3-sync:1.1
Must set access_key, secret_key, and bucket
```

The only change I made was adding `image: plugins/s3-sync:1.1` into the existing `s3_sync` section, which has those three keys set already.

Did something change regarding them?

2017-04-05 09:25 UTC, tboerger commented
The master branch is for >= 0.5 only.