Add flag for custom endpoint
drone-plugins/drone-s3-sync pull request #36
Opened 2017-10-22 07:28 UTC by hdhog

This change provide sync for custom s3 storage.

Add Options
 - Endpoint
 - PathStyle

2017-10-22 07:50 UTC, appleboy approved these changes

2017-10-23 21:28 UTC, tboerger requested changes

2017-10-23 21:28 UTC, tboerger commented on main.go
> +			EnvVar: "PLUGIN_ENDPOINT,S3_ENDPOINT",
Maybe also add S3_SYNC_ENDPOINT to the middle

2017-10-23 21:28 UTC, tboerger commented on aws.go
> +		DisableSSL:       aws.Bool(strings.HasPrefix(p.Endpoint, "http://")),
This should only be set if a custom endpoint have been defined

2017-10-28 10:17 UTC, hdhog commented
@tboerger i fixed it

2017-10-30 08:51 UTC, tboerger commented on aws.go
> +	fmt.Println(p.Endpoint)
Forgot to drop this debugging output?

2017-10-30 09:57 UTC, hdhog commented on aws.go
> +	fmt.Println(p.Endpoint)
yes, fixed

2017-11-02 11:03 UTC, hdhog commented
@tboerger, need some more changes?

2017-11-02 13:13 UTC, tboerger approved these changes

2017-11-02 13:14 UTC, merged